window.KINGMEZO_DEFAULT_CMS = {
  settings: {
    brand: 'Kingmezo',
    adminEmail: 'Chibuzoogbonnaya01@gmail.com',
    adminPassword: '123456',
    contactEmail: 'ChibuzoObonna01@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kingmezo/'
  },
  pages: {
    home: {
      heroNote: 'I build programs that connect young people to education, technology, opportunity, and dignity.',
      heroTitle: 'Impact Led By Community',
      heroLocation: 'Based in Nigeria, working across Africa',
      heroImage: 'assets/drive-projects/big-smile-endo-03.jpg',
      featureImage: 'assets/chiemezo/community-children.jpg',
      aboutTitle: 'Building practical systems for community impact.',
      ctaTitle: 'Ready to build meaningful impact?'
    },
    blog: {
      heroTitle: 'Insight Meets Impact',
      heroBody: 'Practical notes on community development, EdTech, digital inclusion, and youth engagement.',
      heroImage: 'assets/chiemezo/community-gathering.jpg'
    },
    project: {
      heroTitle: 'Project',
      heroBody: 'A curated showcase of projects crafted with strategy, structure, community value, and purpose.',
      heroImage: 'assets/portfolio/boys-champions-strategy.jpeg'
    }
  },
  blogPosts: [
    {
      slug: 'branding-a-strategy-document',
      title: 'Branding a Strategy Document',
      excerpt: 'How a youth advocacy strategy became a clearer visual system for partners and stakeholders.',
      content: 'Boys Champions Strategy shows how branding can make a serious advocacy document easier to understand, present, and trust. The design work focused on structure, hierarchy, photography, and a consistent visual language so the organization could communicate its mission with more confidence.',
      image: 'assets/portfolio/boys-champions-strategy.jpeg',
      date: '2026-07-15',
      readTime: '4 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'designing-digital-literacy',
      title: 'Designing Digital Literacy',
      excerpt: 'How digital programs can become practical, local, and useful for young people.',
      content: 'Digital literacy works best when it is tied to real tasks, confidence, and access. The goal is not only to teach tools, but to help people use those tools for education, work, creativity, and safer participation online.',
      image: 'assets/drive-projects/digital-literacy-01.jpg',
      date: '2026-06-03',
      readTime: '5 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'making-policy-work-locally',
      title: 'Making Policy Work Locally',
      excerpt: 'Turning broad development ideas into practical local coordination.',
      content: 'Policy becomes useful when communities can see what changes in their everyday lives. That means clearer goals, better partners, and feedback from the people affected by the work.',
      image: 'assets/chiemezo/community-gathering.jpg',
      date: '2026-04-22',
      readTime: '4 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'safer-learning-spaces',
      title: 'Safer Learning Spaces',
      excerpt: 'Why safety, dignity, and belonging matter in education programs.',
      content: 'Young people learn better where they feel protected and respected. Safer learning spaces require planning, trusted adults, and systems that respond early to harm.',
      image: 'assets/drive-projects/dont-bully-me-04.jpg',
      date: '2026-05-12',
      readTime: '6 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'youth-participation-matters',
      title: 'Youth Participation Matters',
      excerpt: 'Durable community projects should include young people in decisions, not just events.',
      content: 'Participation is more than attendance. It means young people can shape priorities, contribute ideas, and see evidence that their voices affected the outcome.',
      image: 'assets/chiemezo/hero-community-team.jpg',
      date: '2026-03-18',
      readTime: '5 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    }
  ],
  projectCases: {
    edubridge: {
      title: 'EduBridge Initiative',
      tagline: 'An education support initiative connecting young people to learning tools, mentorship, and opportunity.',
      banner: 'assets/drive-projects/edubridge-01.jpg',
      thumb: 'assets/drive-projects/edubridge-02.jpg',
      summary: 'EduBridge is built to make educational access more practical, supported, and connected to real opportunity.',
      description: 'The initiative brings structure to education-focused support through planning, partner coordination, mentorship pathways, and delivery systems that help young people move from interest to action.',
      client: 'EduBridge',
      industry: 'Education & Youth Development',
      category: 'Project Management',
      duration: 'Program Cycle',
      date: '2026-02-12',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The challenge was creating an education support structure that could stay clear, practical, and useful for young people with different needs.',
      painPoints: ['Limited access to structured learning support and mentorship.', 'Need for clearer coordination between partners, educators, and participants.', 'Programs needed practical tracking, communication, and follow-through.'],
      gallery: ['assets/drive-projects/edubridge-01.jpg', 'assets/drive-projects/edubridge-02.jpg', 'assets/drive-projects/edubridge-03.jpg', 'assets/drive-projects/edubridge-04.jpg'],
      resultTitle: 'A stronger project structure for education support, partner coordination, and youth opportunity.',
      results: ['Clearer program scope and delivery flow.', 'Improved planning structure for outreach and mentorship.', 'Stronger alignment between community needs and educational support.']
    },
    'digital-literacy': {
      title: 'Digital Literacy Program',
      tagline: 'An EduBridge learning program helping young people build practical digital confidence.',
      banner: 'assets/drive-projects/digital-literacy-01.jpg',
      thumb: 'assets/drive-projects/digital-literacy-02.jpg',
      summary: 'Digital Literacy Program supports young learners with access to practical technology exposure and guided learning.',
      description: 'The program sits under EduBridge and focuses on helping students understand computers, digital tools, and learning pathways they can use beyond the classroom.',
      client: 'EduBridge',
      industry: 'Education & Digital Inclusion',
      category: 'Project Management',
      duration: 'Learning Cohort',
      date: '2026-02-20',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The program needed to make digital learning feel accessible, structured, and relevant for young learners.',
      painPoints: ['Learners needed guided exposure to computers and digital tools.', 'The program needed practical classroom coordination.', 'Digital inclusion work needed clear documentation and visual storytelling.'],
      gallery: ['assets/drive-projects/digital-literacy-01.jpg', 'assets/drive-projects/digital-literacy-02.jpg', 'assets/drive-projects/digital-literacy-04.jpg', 'assets/drive-projects/community-outreach-01.jpg'],
      resultTitle: 'A clearer learning experience for digital skills, confidence, and classroom participation.',
      results: ['Supported structured digital literacy sessions.', 'Improved documentation for learning activities.', 'Connected EduBridge goals to practical digital inclusion outcomes.']
    },
    chaise: {
      title: 'CHAISE',
      tagline: "Africa's leading marketplace solution integrating freelancers and business owners together.",
      banner: 'assets/portfolio/chaise-marketplace-screens.jpeg',
      thumb: 'assets/portfolio/chaise-hero-phone.jpeg',
      summary: 'CHAISE connects freelancers and business owners through a focused marketplace experience.',
      description: 'A marketplace solution designed to make hiring, service discovery, and collaboration easier for African freelancers and business owners.',
      client: 'CHAISE',
      industry: 'Marketplace & Technology',
      category: 'Product Dev & Management',
      duration: 'Product Sprint',
      date: '2026-01-18',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The product needed to make trust, discovery, hiring, and project management feel simple for two very different user groups.',
      painPoints: ['Freelancers needed a clearer way to show expertise and access opportunities.', 'Business owners needed faster talent discovery and simpler hiring decisions.', 'The platform needed a product story that could scale across talent, projects, and service categories.'],
      gallery: ['assets/portfolio/chaise-marketplace-screens.jpeg', 'assets/portfolio/chaise-hero-phone.jpeg', 'assets/portfolio/chaise-product-flow.jpeg', 'assets/portfolio/chaise-business-screen.jpeg'],
      resultTitle: 'A clearer product direction for a marketplace built around talent discovery, hiring, and service delivery.',
      results: ['Defined the marketplace positioning and product experience.', 'Clarified user journeys for freelancers and business owners.', 'Created a stronger visual product story for future rollout.']
    },
    'big-smile': {
      title: 'Big Smile Initiative',
      tagline: 'A community care initiative creating moments of support, inclusion, and joy for children and families.',
      banner: 'assets/drive-projects/big-smile-endo-03.jpg',
      thumb: 'assets/drive-projects/big-smile-endo-01.jpg',
      summary: 'Big Smile Initiative brings direct support and human attention to children and families through outreach-led engagement.',
      description: 'The work focuses on dignity, access, and care by bringing people, resources, and local coordination together around practical community needs.',
      client: 'Big Smile Initiative',
      industry: 'Community Development',
      category: 'Community Engagement',
      duration: 'Outreach Cycle',
      date: '2026-06-22',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The initiative needed to translate care into organized outreach that felt warm, trustworthy, and useful to the community.',
      painPoints: ['Families needed practical support that reached them directly.', 'Outreach activities needed clear planning and local coordination.', 'The project needed to preserve dignity while delivering visible care.'],
      gallery: ['assets/drive-projects/big-smile-endo-03.jpg', 'assets/drive-projects/big-smile-endo-01.jpg', 'assets/drive-projects/big-smile-endo-02.jpg'],
      resultTitle: 'A more organized community care experience centered on children, families, and human dignity.',
      results: ['Created a stronger structure for outreach planning.', 'Improved visual storytelling around the initiative.', 'Supported clearer community engagement and participation.']
    },
    'dont-bully-me': {
      title: "Don't Bully Me Campaign",
      tagline: 'A safer learning spaces initiative promoting empathy, confidence, and protection from bullying.',
      banner: 'assets/drive-projects/dont-bully-me-02.jpg',
      thumb: 'assets/drive-projects/dont-bully-me-04.jpg',
      summary: "Don't Bully Me helps young people understand safety, empathy, confidence, and respect in learning environments.",
      description: 'The initiative is designed for school and youth-centered engagement, combining awareness, conversation, and practical community participation.',
      client: "Don't Bully Me",
      industry: 'Youth Advocacy',
      category: 'Community Engagement',
      duration: 'Campaign Cycle',
      date: '2026-05-10',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The project needed to communicate a sensitive issue clearly while creating a safe and encouraging atmosphere for young people.',
      painPoints: ['Students needed safer spaces to discuss bullying and confidence.', 'The message had to be direct without making participants feel exposed.', 'The program needed simple activities that schools and communities could understand.'],
      gallery: ['assets/drive-projects/dont-bully-me-02.jpg', 'assets/drive-projects/dont-bully-me-04.jpg', 'assets/drive-projects/dont-bully-me-01.jpg', 'assets/drive-projects/dont-bully-me-03.jpg'],
      resultTitle: 'A clearer awareness initiative for safer learning spaces and more empathetic youth engagement.',
      results: ['Shaped the initiative around safety, empathy, and confidence.', 'Created a stronger community-facing message.', 'Improved the structure for school and youth participation.']
    },
    'community-outreach': {
      title: 'Community Outreach',
      tagline: 'Community-focused learning and support activities designed around practical local needs.',
      banner: 'assets/drive-projects/community-outreach-02.jpg',
      thumb: 'assets/drive-projects/community-outreach-02.jpg',
      summary: 'Community Outreach brings targeted support, learning moments, and local engagement into spaces where young people can be reached directly.',
      description: 'The work focuses on practical engagement with children and young people, using organized sessions, partner support, and clear communication to meet community needs.',
      client: 'Reves African Foundation',
      industry: 'Community Development',
      category: 'Community Engagement',
      duration: 'Outreach Cycle',
      date: '2026-04-12',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The outreach work needed to stay warm and personal while still being organized enough for documentation, partners, and future planning.',
      painPoints: ['Community activities needed clear coordination and follow-up.', 'The visuals needed to reflect real people and local presence.', 'The work needed to connect learning support with practical outreach.'],
      gallery: ['assets/drive-projects/community-outreach-02.jpg', 'assets/drive-projects/community-outreach-01.jpg'],
      resultTitle: 'A more grounded outreach story that connects learning, care, and local engagement.',
      results: ['Organized community-facing activity documentation.', 'Used relevant Drive images for the correct outreach context.', 'Improved the distinction between outreach, campaigns, and education programs.']
    },
    'boys-champions-strategy': {
      title: 'Boys Champions Strategy',
      tagline: 'A visual strategy and brand document system created for a youth advocacy organization.',
      banner: 'assets/portfolio/boys-champions-strategy.jpeg',
      thumb: 'assets/portfolio/boys-champions-strategy.jpeg',
      summary: 'Boys Champions Strategy is presented here as branding work: a structured visual system for an advocacy organization, not the advocacy project itself.',
      description: 'The work shaped the organization strategy document into a clear, credible, and visually consistent brand asset. The design direction uses strong editorial layouts, blue campaign tones, photography, and clean information hierarchy to make the organization story easier to understand and present.',
      client: 'Boys Champions',
      industry: 'Advocacy Organization',
      category: 'Branding & Strategy',
      duration: 'Brand Document Sprint',
      date: '2026-04-08',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The organization needed a strategy document that could communicate its mission, programs, and long-term direction with clarity and visual trust.',
      painPoints: ['The advocacy message needed a stronger visual structure for partners and stakeholders.', 'The document had to organize dense strategy content without feeling heavy.', 'The identity needed to feel purposeful, credible, and easy to recognize across pages.'],
      gallery: ['assets/portfolio/boys-champions-strategy.jpeg', 'assets/portfolio/boys-champions-strategy-cover.jpeg', 'assets/portfolio/boys-champions-executive-summary.jpeg', 'assets/portfolio/boys-champions-vision-mission.jpeg', 'assets/portfolio/boys-champions-problem-statement.jpeg', 'assets/portfolio/boys-champions-delivery-plan.jpeg'],
      resultTitle: 'A polished brand and strategy document system for presenting Boys Champions with clarity and confidence.',
      results: ['Created a cohesive visual direction for the organization strategy document.', 'Improved hierarchy across cover, executive summary, mission, and program pages.', 'Built a presentation-ready brand asset for stakeholder communication.']
    },
    'dream-digital': {
      title: 'Dream Digital',
      tagline: 'A collection of logo systems, mockups, packaging concepts, and flyer designs for brands, events, and faith communities.',
      banner: 'assets/dream-digital/logos/erca-tote-mockup.jpg',
      thumb: 'assets/dream-digital/flyers/worship-experience.png',
      summary: 'Dream Digital brings together identity work, product packaging, campaign mockups, and event posters with strong visual direction.',
      description: 'The work spans logos, merchandise mockups, packaging layouts, and flyer campaigns. Each piece is organized around the brand or event goal so the final design can be used clearly across digital and physical touchpoints.',
      client: 'Dream Digital Clients',
      industry: 'Branding, Events, and Creative Design',
      category: 'Branding & Strategy',
      duration: 'Selected Works',
      date: '2026-07-09',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The portfolio needed a cleaner way to separate logos, packaging, and flyer campaigns while still showing the range of the design work.',
      painPoints: ['The design pieces needed to be grouped by purpose.', 'Logo and packaging mockups needed room to breathe beside energetic flyer work.', 'The portfolio needed enough structure to make a large image set easy to scan.'],
      gallery: ['assets/dream-digital/logos/erca-tote-mockup.jpg', 'assets/dream-digital/logos/hubertz-label-mockup.jpg', 'assets/dream-digital/logos/souvenirs-mug-mockup.jpg', 'assets/dream-digital/logos/philbrose-packaging.jpg', 'assets/dream-digital/logos/ains-bean-flour-packaging.jpg', 'assets/dream-digital/logos/conversation-starter-cards.jpg', 'assets/dream-digital/logos/pendo-design-co-logo.jpg', 'assets/dream-digital/logos/akuwa-bae-logo.png', 'assets/dream-digital/flyers/worship-experience.png', 'assets/dream-digital/flyers/afro-gospel-sunday.png', 'assets/dream-digital/flyers/faith-for-living.jpg', 'assets/dream-digital/flyers/divine-increase.jpg', 'assets/dream-digital/flyers/dunamis-altars.jpg', 'assets/dream-digital/flyers/spiritual-alignment.jpg', 'assets/dream-digital/flyers/nottingham-worship.jpg', 'assets/dream-digital/flyers/prophetic-amplification.jpg'],
      resultTitle: 'A more organized creative portfolio that separates identity, packaging, policy mockups, and flyer campaigns.',
      results: ['Grouped logos and mockups into a dedicated branding section.', 'Added event flyers as a structured visual campaign set.', 'Created EduData policy page mockups to represent policy-facing design work.']
    },
    kuepass: {
      title: 'Kuepass',
      tagline: 'A corporate minimal identity system across stationery, merchandise, and practical launch collateral.',
      banner: 'assets/portfolio/kuepass-brand-kit.jpeg',
      thumb: 'assets/portfolio/kuepass-cap.jpeg',
      summary: 'Kuepass uses a clean identity system to make the brand feel credible, practical, and easy to recognize.',
      description: 'The work extends the visual identity across stationery, branded objects, and presentation assets with a restrained corporate feel.',
      client: 'Kuepass',
      industry: 'Media & Technology',
      category: 'Branding & Strategy',
      duration: 'Brand Sprint',
      date: '2026-03-04',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The brand needed a minimal identity that could work across physical merchandise, documents, and digital communication.',
      painPoints: ['The identity needed to stay consistent across many formats.', 'Merchandise and stationery had to feel practical, not decorative.', 'The system needed to support recognition without visual clutter.'],
      gallery: ['assets/portfolio/kuepass-brand-kit.jpeg', 'assets/portfolio/kuepass-cap.jpeg', 'assets/portfolio/ambassadors-brand-deck.jpeg', 'assets/portfolio/ambassadors-audience-deck.jpeg'],
      resultTitle: 'A cleaner and more consistent identity system for brand recognition across collateral and merchandise.',
      results: ['Built a practical identity direction for everyday brand use.', 'Extended the system into caps, stationery, and presentation materials.', 'Improved consistency across brand touchpoints.']
    },
    viicsoft: {
      title: 'Viicsoft',
      tagline: 'A corporate minimal identity for a media brand extended into merchandise and launch-ready brand assets.',
      banner: 'assets/portfolio/viicsoft-notebooks.jpeg',
      thumb: 'assets/portfolio/viicsoft-shirts.jpeg',
      summary: 'Viicsoft turns a clean brand identity into a practical merchandise and stationery system.',
      description: 'The identity direction carries across notebooks, shirts, tote bags, bottles, and branded presentation assets with a sharp media-brand tone.',
      client: 'Viicsoft',
      industry: 'Media Brand',
      category: 'Branding & Strategy',
      duration: 'Brand Sprint',
      date: '2026-03-16',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The brand needed a simple but recognizable identity system that could stretch across apparel, stationery, and merchandise.',
      painPoints: ['The identity needed enough flexibility for different product surfaces.', 'Merchandise had to feel cohesive across color, object, and scale.', 'The brand needed sharper presentation for launch and recognition.'],
      gallery: ['assets/portfolio/viicsoft-notebooks.jpeg', 'assets/portfolio/viicsoft-shirts.jpeg', 'assets/portfolio/viicsoft-tote.jpeg', 'assets/portfolio/viicsoft-bottle.jpeg'],
      resultTitle: 'A cohesive visual system that gives Viicsoft stronger recognition across branded merchandise.',
      results: ['Extended the identity across multiple merchandise categories.', 'Improved consistency for apparel and stationery mockups.', 'Created a clean brand presentation for future rollout.']
    }
  },
  media: [
    'assets/chiemezo/hero-community-team.jpg',
    'assets/chiemezo/community-children.jpg',
    'assets/chiemezo/community-gathering.jpg',
    'assets/chiemezo/project-team-planning.jpg',
    'assets/drive-projects/big-smile-endo-01.jpg',
    'assets/drive-projects/big-smile-endo-02.jpg',
    'assets/drive-projects/big-smile-endo-03.jpg',
    'assets/drive-projects/digital-literacy-01.jpg',
    'assets/drive-projects/digital-literacy-02.jpg',
    'assets/drive-projects/digital-literacy-04.jpg',
    'assets/drive-projects/dont-bully-me-01.jpg',
    'assets/drive-projects/dont-bully-me-02.jpg',
    'assets/drive-projects/dont-bully-me-03.jpg',
    'assets/drive-projects/dont-bully-me-04.jpg',
    'assets/drive-projects/edubridge-01.jpg',
    'assets/drive-projects/edubridge-02.jpg',
    'assets/drive-projects/edubridge-03.jpg',
    'assets/drive-projects/edubridge-04.jpg',
    'assets/drive-projects/community-outreach-01.jpg',
    'assets/drive-projects/community-outreach-02.jpg',
    'assets/portfolio/chaise-marketplace-screens.jpeg',
    'assets/portfolio/chaise-hero-phone.jpeg',
    'assets/portfolio/chaise-product-flow.jpeg',
    'assets/portfolio/chaise-business-screen.jpeg',
    'assets/portfolio/boys-champions-strategy.jpeg',
    'assets/portfolio/boys-champions-strategy-cover.jpeg',
    'assets/portfolio/boys-champions-executive-summary.jpeg',
    'assets/portfolio/boys-champions-vision-mission.jpeg',
    'assets/portfolio/boys-champions-problem-statement.jpeg',
    'assets/portfolio/boys-champions-delivery-plan.jpeg',
    'assets/portfolio/kuepass-brand-kit.jpeg',
    'assets/portfolio/viicsoft-notebooks.jpeg'
  ]
};
