window.KINGMEZO_DEFAULT_CMS = {
  settings: {
    brand: 'Kingmezo',
    adminEmail: 'shibuzoogbunaya01@gmail.com',
    adminPassword: '123456',
    contactEmail: 'ChibuzoObonna01@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kingmezo/'
  },
  pages: {
    home: {
      heroNote: 'I build programs that connect young people to education, technology, opportunity, and dignity.',
      heroTitle: 'Impact Led By Community',
      heroLocation: 'Based in Nigeria, working across Africa',
      heroImage: 'assets/chiemezo/hero-community-team.jpg',
      featureImage: 'assets/chiemezo/community-children.jpg',
      aboutTitle: 'Building practical systems for community impact.',
      ctaTitle: 'Ready to build meaningful impact?'
    },
    blog: {
      heroTitle: 'Insight Meets Impact',
      heroBody: 'Practical notes on community development, EdTech, digital inclusion, and youth engagement.',
      heroImage: 'assets/chiemezo/community-gathering.jpg'
    },
    project: {
      heroTitle: 'Project',
      heroBody: 'A curated showcase of projects crafted with strategy, structure, community value, and purpose.',
      heroImage: 'assets/portfolio/chaise-marketplace-screens.jpeg'
    }
  },
  blogPosts: [
    {
      slug: 'designing-digital-literacy',
      title: 'Designing Digital Literacy',
      excerpt: 'How digital programs can become practical, local, and useful for young people.',
      content: 'Digital literacy works best when it is tied to real tasks, confidence, and access. The goal is not only to teach tools, but to help people use those tools for education, work, creativity, and safer participation online.',
      image: 'assets/chiemezo/project-team-planning.jpg',
      date: '2026-06-03',
      readTime: '5 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'making-policy-work-locally',
      title: 'Making Policy Work Locally',
      excerpt: 'Turning broad development ideas into practical local coordination.',
      content: 'Policy becomes useful when communities can see what changes in their everyday lives. That means clearer goals, better partners, and feedback from the people affected by the work.',
      image: 'assets/chiemezo/community-gathering.jpg',
      date: '2026-04-22',
      readTime: '4 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'safer-learning-spaces',
      title: 'Safer Learning Spaces',
      excerpt: 'Why safety, dignity, and belonging matter in education programs.',
      content: 'Young people learn better where they feel protected and respected. Safer learning spaces require planning, trusted adults, and systems that respond early to harm.',
      image: 'assets/chiemezo/community-lineup.jpg',
      date: '2026-05-12',
      readTime: '6 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    },
    {
      slug: 'youth-participation-matters',
      title: 'Youth Participation Matters',
      excerpt: 'Durable community projects should include young people in decisions, not just events.',
      content: 'Participation is more than attendance. It means young people can shape priorities, contribute ideas, and see evidence that their voices affected the outcome.',
      image: 'assets/chiemezo/hero-community-team.jpg',
      date: '2026-03-18',
      readTime: '5 mins read',
      publisher: 'Chibuzo Ogbonnaya',
      status: 'published'
    }
  ],
  projectCases: {
    edubridge: {
      title: 'EduBridge Initiative',
      tagline: 'An education support initiative connecting young people to learning tools, mentorship, and opportunity.',
      banner: 'assets/chiemezo/project-team-planning.jpg',
      thumb: 'assets/chiemezo/community-speaking.jpg',
      summary: 'EduBridge is built to make educational access more practical, supported, and connected to real opportunity.',
      description: 'The initiative brings structure to education-focused support through planning, partner coordination, mentorship pathways, and delivery systems that help young people move from interest to action.',
      client: 'EduBridge',
      industry: 'Education & Youth Development',
      category: 'Project Management',
      duration: 'Program Cycle',
      date: '2026-02-12',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The challenge was creating an education support structure that could stay clear, practical, and useful for young people with different needs.',
      painPoints: ['Limited access to structured learning support and mentorship.', 'Need for clearer coordination between partners, educators, and participants.', 'Programs needed practical tracking, communication, and follow-through.'],
      gallery: ['assets/chiemezo/project-team-planning.jpg', 'assets/chiemezo/community-speaking.jpg', 'assets/chiemezo/project-leadership.jpg', 'assets/chiemezo/project-partners.jpg'],
      resultTitle: 'A stronger project structure for education support, partner coordination, and youth opportunity.',
      results: ['Clearer program scope and delivery flow.', 'Improved planning structure for outreach and mentorship.', 'Stronger alignment between community needs and educational support.']
    },
    chaise: {
      title: 'CHAISE',
      tagline: "Africa's leading marketplace solution integrating freelancers and business owners together.",
      banner: 'assets/portfolio/chaise-marketplace-screens.jpeg',
      thumb: 'assets/portfolio/chaise-hero-phone.jpeg',
      summary: 'CHAISE connects freelancers and business owners through a focused marketplace experience.',
      description: 'A marketplace solution designed to make hiring, service discovery, and collaboration easier for African freelancers and business owners.',
      client: 'CHAISE',
      industry: 'Marketplace & Technology',
      category: 'Product Dev & Management',
      duration: 'Product Sprint',
      date: '2026-01-18',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The product needed to make trust, discovery, hiring, and project management feel simple for two very different user groups.',
      painPoints: ['Freelancers needed a clearer way to show expertise and access opportunities.', 'Business owners needed faster talent discovery and simpler hiring decisions.', 'The platform needed a product story that could scale across talent, projects, and service categories.'],
      gallery: ['assets/portfolio/chaise-marketplace-screens.jpeg', 'assets/portfolio/chaise-hero-phone.jpeg', 'assets/portfolio/chaise-product-flow.jpeg', 'assets/portfolio/chaise-business-screen.jpeg'],
      resultTitle: 'A clearer product direction for a marketplace built around talent discovery, hiring, and service delivery.',
      results: ['Defined the marketplace positioning and product experience.', 'Clarified user journeys for freelancers and business owners.', 'Created a stronger visual product story for future rollout.']
    },
    'big-smile': {
      title: 'Big Smile Initiative',
      tagline: 'A community care initiative creating moments of support, inclusion, and joy for children and families.',
      banner: 'assets/chiemezo/community-children.jpg',
      thumb: 'assets/projects/big-smile-endo.jpg',
      summary: 'Big Smile Initiative brings direct support and human attention to children and families through outreach-led engagement.',
      description: 'The work focuses on dignity, access, and care by bringing people, resources, and local coordination together around practical community needs.',
      client: 'Big Smile Initiative',
      industry: 'Community Development',
      category: 'Community Engagement',
      duration: 'Outreach Cycle',
      date: '2026-06-22',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The initiative needed to translate care into organized outreach that felt warm, trustworthy, and useful to the community.',
      painPoints: ['Families needed practical support that reached them directly.', 'Outreach activities needed clear planning and local coordination.', 'The project needed to preserve dignity while delivering visible care.'],
      gallery: ['assets/chiemezo/community-children.jpg', 'assets/projects/big-smile-endo.jpg', 'assets/chiemezo/community-child.jpg', 'assets/chiemezo/community-gathering.jpg'],
      resultTitle: 'A more organized community care experience centered on children, families, and human dignity.',
      results: ['Created a stronger structure for outreach planning.', 'Improved visual storytelling around the initiative.', 'Supported clearer community engagement and participation.']
    },
    'dont-bully-me': {
      title: "Don't Bully Me Initiative",
      tagline: 'A safer learning spaces initiative promoting empathy, confidence, and protection from bullying.',
      banner: 'assets/chiemezo/community-lineup.jpg',
      thumb: 'assets/chiemezo/community-portrait.jpg',
      summary: "Don't Bully Me helps young people understand safety, empathy, confidence, and respect in learning environments.",
      description: 'The initiative is designed for school and youth-centered engagement, combining awareness, conversation, and practical community participation.',
      client: "Don't Bully Me",
      industry: 'Youth Advocacy',
      category: 'Community Engagement',
      duration: 'Campaign Cycle',
      date: '2026-05-10',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The project needed to communicate a sensitive issue clearly while creating a safe and encouraging atmosphere for young people.',
      painPoints: ['Students needed safer spaces to discuss bullying and confidence.', 'The message had to be direct without making participants feel exposed.', 'The program needed simple activities that schools and communities could understand.'],
      gallery: ['assets/chiemezo/community-lineup.jpg', 'assets/chiemezo/community-gathering.jpg', 'assets/chiemezo/community-portrait.jpg', 'assets/chiemezo/community-culture.jpg'],
      resultTitle: 'A clearer awareness initiative for safer learning spaces and more empathetic youth engagement.',
      results: ['Shaped the initiative around safety, empathy, and confidence.', 'Created a stronger community-facing message.', 'Improved the structure for school and youth participation.']
    },
    kuepass: {
      title: 'Kuepass',
      tagline: 'A corporate minimal identity system across stationery, merchandise, and practical launch collateral.',
      banner: 'assets/portfolio/kuepass-brand-kit.jpeg',
      thumb: 'assets/portfolio/kuepass-cap.jpeg',
      summary: 'Kuepass uses a clean identity system to make the brand feel credible, practical, and easy to recognize.',
      description: 'The work extends the visual identity across stationery, branded objects, and presentation assets with a restrained corporate feel.',
      client: 'Kuepass',
      industry: 'Media & Technology',
      category: 'Branding & Strategy',
      duration: 'Brand Sprint',
      date: '2026-03-04',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The brand needed a minimal identity that could work across physical merchandise, documents, and digital communication.',
      painPoints: ['The identity needed to stay consistent across many formats.', 'Merchandise and stationery had to feel practical, not decorative.', 'The system needed to support recognition without visual clutter.'],
      gallery: ['assets/portfolio/kuepass-brand-kit.jpeg', 'assets/portfolio/kuepass-cap.jpeg', 'assets/portfolio/ambassadors-brand-deck.jpeg', 'assets/portfolio/ambassadors-audience-deck.jpeg'],
      resultTitle: 'A cleaner and more consistent identity system for brand recognition across collateral and merchandise.',
      results: ['Built a practical identity direction for everyday brand use.', 'Extended the system into caps, stationery, and presentation materials.', 'Improved consistency across brand touchpoints.']
    },
    viicsoft: {
      title: 'Viicsoft',
      tagline: 'A corporate minimal identity for a media brand extended into merchandise and launch-ready brand assets.',
      banner: 'assets/portfolio/viicsoft-notebooks.jpeg',
      thumb: 'assets/portfolio/viicsoft-shirts.jpeg',
      summary: 'Viicsoft turns a clean brand identity into a practical merchandise and stationery system.',
      description: 'The identity direction carries across notebooks, shirts, tote bags, bottles, and branded presentation assets with a sharp media-brand tone.',
      client: 'Viicsoft',
      industry: 'Media Brand',
      category: 'Branding & Strategy',
      duration: 'Brand Sprint',
      date: '2026-03-16',
      publisher: 'Chibuzo Ogbonnaya',
      challenge: 'The brand needed a simple but recognizable identity system that could stretch across apparel, stationery, and merchandise.',
      painPoints: ['The identity needed enough flexibility for different product surfaces.', 'Merchandise had to feel cohesive across color, object, and scale.', 'The brand needed sharper presentation for launch and recognition.'],
      gallery: ['assets/portfolio/viicsoft-notebooks.jpeg', 'assets/portfolio/viicsoft-shirts.jpeg', 'assets/portfolio/viicsoft-tote.jpeg', 'assets/portfolio/viicsoft-bottle.jpeg'],
      resultTitle: 'A cohesive visual system that gives Viicsoft stronger recognition across branded merchandise.',
      results: ['Extended the identity across multiple merchandise categories.', 'Improved consistency for apparel and stationery mockups.', 'Created a clean brand presentation for future rollout.']
    }
  },
  media: [
    'assets/chiemezo/hero-community-team.jpg',
    'assets/chiemezo/community-children.jpg',
    'assets/chiemezo/community-gathering.jpg',
    'assets/chiemezo/project-team-planning.jpg',
    'assets/chiemezo/project-field-coordination.jpg',
    'assets/portfolio/chaise-marketplace-screens.jpeg',
    'assets/portfolio/chaise-hero-phone.jpeg',
    'assets/portfolio/kuepass-brand-kit.jpeg',
    'assets/portfolio/viicsoft-notebooks.jpeg'
  ]
};
